#include <Rcpp.h>
#include "edi_build_flags.h"

//' Return EDI Build Information (C++ Backend)
//'
//' Returns the compiler and package build metadata that was baked into the currently
//' loaded EDI shared object \strong{at compile time} (via preprocessor macros defined
//' in \code{edi_build_flags.h}, generated by the package's build tooling), not
//' anything queried live from the running system. This is intended for benchmark
//' reports and reproducibility audits where the exact compiler, flags, and build
//' environment used to produce the installed binary matter (e.g. explaining
//' performance differences between two installations of the same package version, or
//' confirming a binary was built with a particular optimization/vectorization
//' configuration).
//'
//' @details
//' Every field is a fixed string or boolean baked in when the C++ source was compiled
//' (via preprocessor macro substitution); calling this function multiple times within
//' the same R session always returns identical values, and the values reflect the
//' build environment, not the environment the function happens to be \emph{called}
//' from. If EDI is reinstalled/recompiled, existing R sessions that already loaded the
//' old shared object continue to report the old build's metadata until they restart
//' and load the new one.
//'
//' @return A named list with the following fields, all length-1 character strings
//'   unless noted otherwise:
//'   \describe{
//'     \item{capture_method}{How the build metadata below was captured by the
//'       package's build tooling (\code{EDI_BUILD_CAPTURE_METHOD}).}
//'     \item{build_timestamp}{Timestamp of compilation (\code{EDI_BUILD_TIMESTAMP}).}
//'     \item{build_host}{Hostname of the machine that compiled this binary
//'       (\code{EDI_BUILD_HOST}).}
//'     \item{r_home}{\code{R_HOME} of the R installation used to build the package.}
//'     \item{r_version}{R version string used to build the package.}
//'     \item{r_cxx20}{The C++20 compiler command R's build configuration reported.}
//'     \item{r_cxx20std}{The C++ standard flag (e.g. \code{-std=gnu++20}) used.}
//'     \item{r_cxx20flags}{Additional C++20 compiler flags from R's configuration.}
//'     \item{r_shlib_openmp_cxxflags}{OpenMP C++ flags R's configuration supplies for
//'       shared-library builds (empty if OpenMP support was not available/enabled).}
//'     \item{env_edi_portable, env_edi_disable_vectorization, env_edi_native_speed,
//'       env_edi_native_lto}{The values (or default/unset indicator) of the
//'       corresponding \code{EDI_*} environment variables that were set at build time
//'       to control portable-vs-native code generation, vectorization, and link-time
//'       optimization; see the package's build documentation for what each controls.}
//'     \item{pkg_cppflags, pkg_cxxflags, pkg_libs}{The package-level \code{PKG_CPPFLAGS}/
//'       \code{PKG_CXXFLAGS}/\code{PKG_LIBS} used when compiling/linking EDI's C++
//'       sources.}
//'     \item{compiler}{The compiler identification string (\code{__VERSION__}).}
//'     \item{compiler_optimize_macro}{Logical; \code{TRUE} iff the compiler defined
//'       \code{__OPTIMIZE__} (i.e. optimizations were enabled) when this translation
//'       unit was compiled.}
//'     \item{compiler_fast_math_macro}{Logical; \code{TRUE} iff \code{__FAST_MATH__}
//'       was defined (i.e. non-IEEE-compliant fast-math optimizations were enabled),
//'       which can affect floating-point reproducibility/edge-case behavior (NaN/Inf
//'       handling, exact rounding) relative to a standard-compliant build.}
//'     \item{eigen_dont_vectorize_macro}{Logical; \code{TRUE} iff
//'       \code{EIGEN_DONT_VECTORIZE} was defined, disabling Eigen's SIMD
//'       vectorization for this build (e.g. for portability to CPUs lacking the
//'       vector instructions a native build would target).}
//'   }
//' @export
//' @examples
//' info = edi_build_info_cpp()
//' info$pkg_cxxflags
// [[Rcpp::export]]
Rcpp::List edi_build_info_cpp() {
    return Rcpp::List::create(
        Rcpp::Named("capture_method") = EDI_BUILD_CAPTURE_METHOD,
        Rcpp::Named("build_timestamp") = EDI_BUILD_TIMESTAMP,
        Rcpp::Named("build_host") = EDI_BUILD_HOST,
        Rcpp::Named("r_home") = EDI_BUILD_R_HOME,
        Rcpp::Named("r_version") = EDI_BUILD_R_VERSION,
        Rcpp::Named("r_cxx20") = EDI_BUILD_R_CXX20,
        Rcpp::Named("r_cxx20std") = EDI_BUILD_R_CXX20STD,
        Rcpp::Named("r_cxx20flags") = EDI_BUILD_R_CXX20FLAGS,
        Rcpp::Named("r_shlib_openmp_cxxflags") = EDI_BUILD_R_SHLIB_OPENMP_CXXFLAGS,
        Rcpp::Named("env_edi_portable") = EDI_BUILD_ENV_EDI_PORTABLE,
        Rcpp::Named("env_edi_disable_vectorization") = EDI_BUILD_ENV_EDI_DISABLE_VECTORIZATION,
        Rcpp::Named("env_edi_native_speed") = EDI_BUILD_ENV_EDI_NATIVE_SPEED,
        Rcpp::Named("env_edi_native_lto") = EDI_BUILD_ENV_EDI_NATIVE_LTO,
        Rcpp::Named("pkg_cppflags") = EDI_BUILD_PKG_CPPFLAGS,
        Rcpp::Named("pkg_cxxflags") = EDI_BUILD_PKG_CXXFLAGS,
        Rcpp::Named("pkg_libs") = EDI_BUILD_PKG_LIBS,
        Rcpp::Named("compiler") = __VERSION__,
#ifdef __OPTIMIZE__
        Rcpp::Named("compiler_optimize_macro") = true,
#else
        Rcpp::Named("compiler_optimize_macro") = false,
#endif
#ifdef __FAST_MATH__
        Rcpp::Named("compiler_fast_math_macro") = true,
#else
        Rcpp::Named("compiler_fast_math_macro") = false,
#endif
#ifdef EIGEN_DONT_VECTORIZE
        Rcpp::Named("eigen_dont_vectorize_macro") = true
#else
        Rcpp::Named("eigen_dont_vectorize_macro") = false
#endif
    );
}
