#!/usr/bin/env bash
# Verifies every unity-build wrapper (R/EDI/src/unity_NN.cpp, generated by
# R/EDI/configure when EDI_UNITY=1, the default) still syntax-checks cleanly
# -- a standing regression gate against a *future* kernel file introducing a
# new collision (duplicated anonymous-namespace helper, repeated-default
# *_internal declaration, etc.), the exact bug family
# package_metadata/finished_features/unity_build_collision_audit.md found
# and fixed for every file present as of 2026-08-16.
#
# Runs configure fresh in an ISOLATED TEMPORARY COPY of R/EDI, not the real
# working tree: a developer doing targeted/incremental local kernel work may
# deliberately have EDI_UNITY=0 configured locally (see that setting's own
# comment in R/EDI/configure) -- in which case a plain `R CMD INSTALL` in
# this repo would silently not exercise the unity grouping at all, and this
# check would give a false sense of coverage if it just deferred to whatever
# the working tree already has configured. Never writes to R/EDI/src.
#
# -fsyntax-only, not a real compile+link -- matches
# unity_build_collision_audit.md's own verification method, and is what
# actually matters here: this check exists to catch a *collision* (two
# symbols that can't coexist in one translation unit), not to validate
# runtime correctness (a real `R CMD INSTALL`, already run by pre-push
# whenever C++ files change, covers that).
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
edi_src="$repo_root/R/EDI"

work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

# configure only reads/writes R/EDI/src -- copy just that (not R/, man/,
# etc.) to keep this fast enough for a pre-push hook. Excludes any
# already-generated build artifacts (.o/.d/.so/unity_*.cpp -- all
# .gitignore'd in the real tree, but a leftover local build could still have
# them on disk) so configure's own file discovery sees exactly the same
# member .cpp set a clean checkout would.
echo "check_unity_build_safety: copying R/EDI/src into a scratch dir ..."
mkdir -p "$work_dir/EDI"
cp "$edi_src/configure" "$edi_src/configure.win" "$work_dir/EDI/"
mkdir -p "$work_dir/EDI/src"
cp "$edi_src"/src/*.cpp "$edi_src"/src/*.h "$work_dir/EDI/src/"
rm -f "$work_dir"/EDI/src/unity_*.cpp

echo "check_unity_build_safety: running configure (EDI_UNITY=1, EDI_PORTABLE=1) in the scratch copy ..."
( cd "$work_dir/EDI" && R_HOME="$(R RHOME)" EDI_UNITY=1 EDI_PORTABLE=1 ./configure ) > /dev/null

shopt -s nullglob
unity_files=("$work_dir"/EDI/src/unity_*.cpp)
shopt -u nullglob
if [ "${#unity_files[@]}" -eq 0 ]; then
	echo "check_unity_build_safety: configure produced no unity_*.cpp wrappers -- nothing to check." >&2
	echo "check_unity_build_safety: (expected 10 -- see R/EDI/configure's generate_unity_wrappers)." >&2
	exit 1
fi

# Resolve the same include paths R CMD INSTALL itself uses for these
# packages (LinkingTo: RcppEigen, RcppNumerical; Imports: Rcpp), via R
# itself rather than hardcoding a path -- portable across machines/CI.
r_include="$(R RHOME)/include"
rcpp_include="$(Rscript -e 'cat(system.file("include", package = "Rcpp"))')"
rcppeigen_include="$(Rscript -e 'cat(system.file("include", package = "RcppEigen"))')"
rcppnumerical_include="$(Rscript -e 'cat(system.file("include", package = "RcppNumerical"))')"

echo "check_unity_build_safety: syntax-checking ${#unity_files[@]} unity translation units in parallel ..."
pids=()
logs=()
for f in "${unity_files[@]}"; do
	name="$(basename "$f")"
	log="$work_dir/${name%.cpp}.log"
	logs+=("$log")
	(
		g++ -std=gnu++17 -fopenmp -DNDEBUG -DEIGEN_NO_DEBUG -Wno-ignored-attributes -fsyntax-only \
			-I"$r_include" -I"$rcpp_include" -I"$rcppeigen_include" -I"$rcppnumerical_include" \
			-I"$work_dir/EDI/src" "$f" > "$log" 2>&1
	) &
	pids+=("$!")
done

failed=0
for i in "${!pids[@]}"; do
	if ! wait "${pids[$i]}"; then
		failed=1
		name="$(basename "${unity_files[$i]}")"
		echo "check_unity_build_safety: $name FAILED:" >&2
		cat "${logs[$i]}" >&2
		echo "check_unity_build_safety: (a collision between $name's member .cpp files -- see the #include list at the top of that file for which ones -- or a genuinely broken file. Cross-reference against unity_build_collision_audit.md's fix patterns: hoist a shared header, or rename a diverged duplicate.)" >&2
	fi
done

if [ "$failed" = "1" ]; then
	echo "check_unity_build_safety: one or more unity translation units FAILED to compile." >&2
	exit 1
fi

echo "check_unity_build_safety: all ${#unity_files[@]} unity translation units compile cleanly."
