#!/usr/bin/env python3
"""Verify EDI/src's migrated numeric cores are genuinely Rcpp/R-free.

See package_metadata/new_feature_plans/sexp_removal_rcppeigen_conversion_spec.md
(TODO-3, Testing step 5, Acceptance Criteria) for why this exists: the core
functions built during that migration are supposed to be pure Eigen/C++, so
they can be shared with the Python (pybind11) build without duplicating any
math. Nothing in the C++ type system enforces that boundary -- a stray
`Rcpp::stop(...)` or `SEXP` parameter added later would compile silently
(RcppEigen.h is still pulled in for the Eigen types), quietly reintroducing
the R coupling the migration removed. This script is that enforcement.

How it decides what counts as "core":

The dominant pattern in this codebase (see fast_gamma_functions.h's header
comment) is same-file split: a core function and its thin Rcpp wrapper live
in the same .cpp file, distinguished by `#ifdef EDI_CORE_ONLY` / `#ifndef
EDI_CORE_ONLY` guards -- exactly the macro the real Python/pybind11 CMake
build defines when compiling these files (see python/CMakeLists.txt). So
rather than grep the whole file (which would immediately false-positive on
every file's R-build branch), this statically evaluates -- per file, without
invoking a real preprocessor or requiring a compiler -- which lines would
survive if EDI_CORE_ONLY were defined, by tracking #if/#ifdef/#ifndef/#else/
#endif nesting. Only *_core.cpp/*_core.h files (whole-file core, "File
Structure" option 2 in the spec) are checked in full regardless of guards.
Files with no EDI_CORE_ONLY guards at all are legacy/not-yet-migrated and
are out of scope -- they'll be picked up automatically once migrated.

Comments and string/char literals are stripped before token-matching, so a
doc comment that merely *mentions* "SEXP" or "Rcpp::" while explaining the
convention (there are several in this codebase) doesn't trip a false
positive.

A surviving line fails the check if it contains:
  - the token SEXP
  - a qualified Rcpp:: name (e.g. Rcpp::stop, Rcpp::wrap)
  - an #include naming a Rcpp header (Rcpp.h, RcppEigen.h, Rcpp/*.h, ...)
    -- RcppEigen.h is only tolerated on the *non*-core-only branch (the
    established convention swaps it for plain <Eigen/Dense> under
    EDI_CORE_ONLY; see fast_gamma_functions.h), so it's a real violation if
    it ever shows up in the surviving-under-EDI_CORE_ONLY region.
"""
import os
import re
import sys

# Deliberately Rcpp-coupled by design, not part of any core:
#   RcppExports.cpp    -- generated by Rcpp::compileAttributes(), always
#                          R-facing.
#   result_map_rcpp.h  -- the one sanctioned bridge file that includes both
#                          result_map.h and Rcpp.h (see the spec's Target
#                          Architecture section); never included by a core
#                          .cpp file.
EXCLUDE_FILES = {"RcppExports.cpp", "result_map_rcpp.h"}

DIRECTIVE_RE = re.compile(r'^\s*#\s*(ifdef|ifndef|if|elif|else|endif)\b(.*)$')
CORE_ONLY_DEFINED_RE = re.compile(r'defined\s*\(\s*EDI_CORE_ONLY\s*\)')
CORE_ONLY_NOT_DEFINED_RE = re.compile(r'!\s*defined\s*\(\s*EDI_CORE_ONLY\s*\)')
CORE_ONLY_TOKEN_RE = re.compile(r'\bEDI_CORE_ONLY\b')

INCLUDE_RCPP_RE = re.compile(r'#\s*include\s*[<"]([^<">]*Rcpp[^<">]*)[<">]')
SEXP_RE = re.compile(r'\bSEXP\b')
RCPP_NS_RE = re.compile(r'\bRcpp::')


def strip_comments_and_strings(text):
    """Blank out // and /* */ comments and "..."/'...' literal contents,
    preserving every newline so line numbers of the result line up with the
    original file."""
    out = []
    i, n = 0, len(text)
    state = "code"
    while i < n:
        c = text[i]
        if state == "code":
            if c == "/" and i + 1 < n and text[i + 1] == "/":
                state = "line_comment"
                out.append("  ")
                i += 2
                continue
            if c == "/" and i + 1 < n and text[i + 1] == "*":
                state = "block_comment"
                out.append("  ")
                i += 2
                continue
            if c == '"':
                state = "string"
                out.append(" ")
                i += 1
                continue
            if c == "'":
                state = "char"
                out.append(" ")
                i += 1
                continue
            out.append(c)
            i += 1
        elif state == "line_comment":
            if c == "\n":
                state = "code"
                out.append(c)
            else:
                out.append(" ")
            i += 1
        elif state == "block_comment":
            if c == "*" and i + 1 < n and text[i + 1] == "/":
                state = "code"
                out.append("  ")
                i += 2
            else:
                out.append("\n" if c == "\n" else " ")
                i += 1
        elif state == "string":
            if c == "\\" and i + 1 < n:
                out.append("  ")
                i += 2
                continue
            if c == '"':
                state = "code"
                out.append(" ")
            else:
                out.append("\n" if c == "\n" else " ")
            i += 1
        elif state == "char":
            if c == "\\" and i + 1 < n:
                out.append("  ")
                i += 2
                continue
            if c == "'":
                state = "code"
                out.append(" ")
            else:
                out.append("\n" if c == "\n" else " ")
            i += 1
    return "".join(out)


def scan_file(path):
    """Returns (violations, saw_core_only_guard) where violations is a list
    of (lineno, reason) for lines that would survive an EDI_CORE_ONLY
    compile but still reference Rcpp/SEXP."""
    with open(path, encoding="utf-8", errors="replace") as f:
        raw_text = f.read()
    raw_lines = raw_text.splitlines()
    clean_lines = strip_comments_and_strings(raw_text).splitlines()

    violations = []
    saw_core_only_guard = False
    # Stack of frame kinds for nested #if/#ifdef/#ifndef:
    #   'core_include' -- this branch only survives when EDI_CORE_ONLY IS defined
    #   'core_exclude' -- this branch only survives when EDI_CORE_ONLY is NOT defined
    #   'neutral'      -- condition unrelated to EDI_CORE_ONLY; inherits parent
    stack = []

    def currently_excluded():
        return any(k == "core_exclude" for k in stack)

    for lineno, raw in enumerate(raw_lines, 1):
        m = DIRECTIVE_RE.match(raw)
        if m:
            kind, rest = m.group(1), m.group(2)
            if kind in ("ifdef", "ifndef", "if"):
                if kind == "ifdef":
                    is_defined_branch = CORE_ONLY_TOKEN_RE.search(rest) is not None
                    is_core_directive = is_defined_branch
                elif kind == "ifndef":
                    is_notdefined_branch = CORE_ONLY_TOKEN_RE.search(rest) is not None
                    is_core_directive = is_notdefined_branch
                else:  # #if
                    is_defined_branch = CORE_ONLY_DEFINED_RE.search(rest) is not None
                    is_notdefined_branch = CORE_ONLY_NOT_DEFINED_RE.search(rest) is not None
                    is_core_directive = is_defined_branch or is_notdefined_branch

                if is_core_directive:
                    saw_core_only_guard = True
                    if kind == "ifdef" or (kind == "if" and is_defined_branch):
                        stack.append("core_include")
                    else:  # ifndef, or `#if !defined(EDI_CORE_ONLY)`
                        stack.append("core_exclude")
                else:
                    stack.append("neutral")
            elif kind == "elif":
                # EDI_CORE_ONLY guards in this codebase are simple ifdef/
                # ifndef/else, never elif chains; treat conservatively as
                # neutral (included) rather than guess.
                if stack:
                    stack[-1] = "neutral"
            elif kind == "else":
                if stack:
                    top = stack[-1]
                    if top == "core_include":
                        stack[-1] = "core_exclude"
                    elif top == "core_exclude":
                        stack[-1] = "core_include"
                    # neutral#else stays neutral
            elif kind == "endif":
                if stack:
                    stack.pop()
            continue  # directive line itself is never scanned for violations

        if currently_excluded():
            continue

        clean = clean_lines[lineno - 1] if lineno - 1 < len(clean_lines) else ""

        m_inc = INCLUDE_RCPP_RE.search(clean)
        if m_inc:
            violations.append((lineno, f"#include of Rcpp header <{m_inc.group(1)}>"))
            continue
        if SEXP_RE.search(clean):
            violations.append((lineno, "SEXP token"))
            continue
        if RCPP_NS_RE.search(clean):
            violations.append((lineno, "Rcpp:: qualified reference"))
            continue

    return violations, saw_core_only_guard


def main():
    if len(sys.argv) < 2:
        print(f"usage: {sys.argv[0]} <path-to-EDI/src>", file=sys.stderr)
        return 2
    src_dir = sys.argv[1]
    if not os.path.isdir(src_dir):
        print(f"error: {src_dir} is not a directory", file=sys.stderr)
        return 2

    checked = []
    skipped_unmigrated = []
    all_violations = []

    for fname in sorted(os.listdir(src_dir)):
        if not (fname.endswith(".cpp") or fname.endswith(".h")):
            continue
        if fname in EXCLUDE_FILES:
            continue
        path = os.path.join(src_dir, fname)
        is_whole_core = fname.endswith("_core.cpp") or fname.endswith("_core.h")

        violations, saw_guard = scan_file(path)

        if not is_whole_core and not saw_guard:
            skipped_unmigrated.append(fname)
            continue

        checked.append(fname)
        for lineno, reason in violations:
            all_violations.append((fname, lineno, reason))

    for fname, lineno, reason in all_violations:
        print(f"{os.path.join(os.path.relpath(src_dir), fname)}:{lineno}: {reason}")

    print(
        f"\ncheck_core_no_rcpp: {len(checked)} migrated file(s) checked, "
        f"{len(skipped_unmigrated)} not-yet-migrated file(s) skipped, "
        f"{len(all_violations)} violation(s) found."
    )
    if all_violations:
        print("FAIL: core region(s) above still reference Rcpp/SEXP.", file=sys.stderr)
        return 1
    print("OK: every migrated core region is Rcpp/SEXP-free.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
