# Demo-side helper: build KK-style matched pairs from observed data by optimal
# bipartite caliper matching, with every unmatched subject placed in the reservoir.
#
# Not part of the EDI package. Used by demo scripts generated by edi_inference_demo()
# (new_feature_plans/demo_generator.md, TODO-10). Requires optmatch, listed in
# EDI's Suggests.
#
# Bipartite matching is the right model here: treatment is observed, so
# treated and control subjects form the two sides and every pair is
# cross-arm by construction. Pairs beyond the caliper are absent edges, so a
# subject with no admissible partner is left unmatched and goes to the reservoir.
#
# Caliper = Inf gives plain optimal bipartite matching with no caliper, as used
# for demos of DesignFixedBinaryMatch.
#
# Usage:
#   source("R/package_metadata/demo_helpers/caliper_reservoir_pairs.R")
#   res <- caliper_reservoir_pairs(X, w, caliper = 0.5)
#   res$pairs      # k x 2 matrix of row indices, column 1 = w==1 member, column 2 = w==0 member
#   res$reservoir  # integer vector of row indices not in any pair
#   res$match_rate # share of subjects in a pair

caliper_reservoir_pairs <- function(X, w, caliper = 0.5, mahal_match = FALSE) {
  if (!requireNamespace("optmatch", quietly = TRUE)) {
    stop("the optmatch package is required (listed in EDI's Suggests)", call. = FALSE)
  }
  X <- as.matrix(X)
  w <- as.integer(w)
  n <- nrow(X)
  if (length(w) != n) stop("length(w) must equal nrow(X)", call. = FALSE)
  if (!all(w %in% c(0L, 1L))) stop("w must be 0/1", call. = FALSE)
  treated <- which(w == 1L)
  controls <- which(w == 0L)
  if (length(treated) == 0L || length(controls) == 0L) stop("both arms must be present", call. = FALSE)
  if (!is.numeric(caliper) || length(caliper) != 1L || caliper <= 0) {
    stop("caliper must be a single positive number (Inf for no caliper)", call. = FALSE)
  }

  # Drop constant columns, then put covariates on a common scale so the
  # caliper means the same thing for every covariate.
  keep <- apply(X, 2L, function(col) stats::sd(col) > 0)
  X <- X[, keep, drop = FALSE]
  if (ncol(X) == 0L) stop("no non-constant covariates", call. = FALSE)

  if (mahal_match) {
    S <- stats::cov(X)
    U <- tryCatch(chol(solve(S)), error = function(e) chol(solve(S + diag(1e-8, ncol(S)))))
    Z <- X %*% t(U)
  } else {
    Z <- scale(X)
  }

  # Treated-by-control distances, Inf outside the caliper (no edge).
  dmat <- as.matrix(stats::dist(Z))[treated, controls, drop = FALSE]
  dmat[dmat > caliper] <- Inf

  # optmatch::pairmatch() needs a perfect match, so it returns all NA when some
  # subjects cannot be paired. Allow leftovers by augmenting to a square matrix:
  # each subject may instead be "unmatched" against its own dummy, at cost
  # `unmatched_cost`. A pair costs at most that value, and leaving both members
  # out costs 2 * unmatched_cost, so the optimum pairs whenever a pair is
  # admissible. With no caliper, the largest finite distance serves as the cost.
  unmatched_cost <- if (is.finite(caliper)) caliper else max(dmat[is.finite(dmat)])
  n_t <- length(treated)
  n_c <- length(controls)
  big <- matrix(Inf, n_t + n_c, n_c + n_t)
  big[seq_len(n_t), seq_len(n_c)] <- dmat
  big[cbind(seq_len(n_t), n_c + seq_len(n_t))] <- unmatched_cost
  big[cbind(n_t + seq_len(n_c), seq_len(n_c))] <- unmatched_cost
  big[(n_t + 1L):(n_t + n_c), (n_c + 1L):(n_c + n_t)] <- 0
  dimnames(big) <- list(
    c(paste0("T", seq_len(n_t)), paste0("D", seq_len(n_c))),
    c(paste0("C", seq_len(n_c)), paste0("E", seq_len(n_t)))
  )

  # pairmatch() warns that order is not guaranteed without a `data` argument.
  # That does not apply here: the matches are read back by name.
  m <- suppressWarnings(optmatch::pairmatch(big))
  m <- m[!is.na(m)]
  groups <- split(names(m), as.character(m))
  is_pair <- vapply(groups, function(g) any(startsWith(g, "T")) && any(startsWith(g, "C")), logical(1))
  groups <- groups[is_pair]
  pairs <- do.call(rbind, lapply(groups, function(g) {
    c(treated[as.integer(sub("^T", "", g[startsWith(g, "T")]))],
      controls[as.integer(sub("^C", "", g[startsWith(g, "C")]))])
  }))
  if (is.null(pairs)) pairs <- matrix(integer(0), ncol = 2L)
  pairs <- matrix(as.integer(pairs), ncol = 2L)

  reservoir <- setdiff(seq_len(n), as.integer(pairs))
  list(
    pairs = pairs,
    reservoir = as.integer(reservoir),
    match_rate = 2 * nrow(pairs) / n
  )
}

# Self-check when run directly.
if (sys.nframe() == 0L) {
  set.seed(1)
  n <- 200
  X <- cbind(x1 = rnorm(n), x2 = rnorm(n))
  w <- rbinom(n, 1, plogis(0.5 * X[, 1]))
  res <- caliper_reservoir_pairs(X, w, caliper = 0.5)
  stopifnot(all(w[res$pairs[, 1]] == 1L), all(w[res$pairs[, 2]] == 0L))
  all_ids <- c(as.vector(res$pairs), res$reservoir)
  stopifnot(length(all_ids) == n, !anyDuplicated(all_ids))
  Z <- scale(X)
  pair_d <- sqrt(rowSums((Z[res$pairs[, 1], , drop = FALSE] - Z[res$pairs[, 2], , drop = FALSE])^2))
  stopifnot(all(pair_d <= 0.5 + 1e-12))
  cat(sprintf("pairs=%d reservoir=%d match_rate=%.2f\n",
              nrow(res$pairs), length(res$reservoir), res$match_rate))
}

# Find the caliper that leaves about `prop_reservoir` of subjects unmatched.
# Larger calipers admit more pairs, so the reservoir share falls as the caliper
# grows; bisection on log(caliper) finds the crossing. Returns the caliper,
# the reservoir share it achieves, and the match result. The achieved share is
# discrete (2 subjects per pair), so it may differ from the target by up to
# 2/n.
caliper_for_reservoir <- function(X, w, prop_reservoir = 0.2, mahal_match = FALSE,
                                  max_iter = 40L) {
  if (!is.numeric(prop_reservoir) || length(prop_reservoir) != 1L ||
      prop_reservoir < 0 || prop_reservoir >= 1) {
    stop("prop_reservoir must be a number in [0, 1)", call. = FALSE)
  }
  n <- nrow(as.matrix(X))
  share <- function(cal) {
    1 - caliper_reservoir_pairs(X, w, caliper = cal, mahal_match = mahal_match)$match_rate
  }
  lo <- log(1e-4)
  Z <- scale(as.matrix(X)[, apply(as.matrix(X), 2L, stats::sd) > 0, drop = FALSE])
  hi <- log(max(stats::dist(Z)))
  best <- NULL
  for (i in seq_len(max_iter)) {
    mid <- (lo + hi) / 2
    cal <- exp(mid)
    s <- share(cal)
    if (is.null(best) || abs(s - prop_reservoir) < abs(best$share - prop_reservoir)) {
      best <- list(caliper = cal, share = s)
    }
    if (s > prop_reservoir) lo <- mid else hi <- mid
    if (hi - lo < 1e-4) break
  }
  c(best, list(target = prop_reservoir, n = n,
               result = caliper_reservoir_pairs(X, w, caliper = best$caliper, mahal_match = mahal_match)))
}
